version: "2"
services:
  web:
    build: 
      context: ./siteA
    ports:
      - "8080:80"
  app: 
    image: nginx:latest
    build: 
      context: ./siteB
    ports:
      - "8181:80"
    volumes: 
       - ./html/var/www/html:ro

